blank_issues_enabled: false
contact_links:
  - name: 📚 Documentação do Sistema
    url: https://github.com/juliannaPaz/java-copilot-code-agent/tree/main/docs
    about: Consulte a documentação para dúvidas sobre o funcionamento do sistema
  - name: 💬 Suporte Técnico Urgente
    url: mailto:suporte.mergington@escola.edu.br
    about: Para problemas críticos que impedem o trabalho, entre em contato diretamente